# @package _global_

# specify here default training configuration
defaults:
    - default_trainer.yaml # do not change
    - celltrack_model_3d.yaml # can be changed
    - datamodule_multiSequence.yaml # can be changed
    - default_callbacks.yaml  # do not change
    - many_loggers.yaml  # do not change
    - infer.yaml

one_hot: True
separate_models: True

work_dir: /home/ubuntu/cell-tracker-gnn
data_root: /mnt/jiahanli/cell-tracker-gnn
data_dir: ${data_root}/data
exp_name: test
log_dir: ${data_root}/logs/logs_${exp_name}

debug: False

# disable python warnings if they annoy you
disable_warnings: True
