datamodule:
  data_dir: ${data_dir}  # data_dir is specified in config.yaml
  batch_size: 8
  num_workers: 0
  pin_memory: False
  train_val_test_split: [80, 20, 0]
  sampler_type: 'from_both'

  dataset_params:
    num_frames: 10
    type_file: 'csv'
    produce_gt: 'simple'
    main_path: /home/ubuntu/cell-tracker-gnn/data/ct_features/Fluo-N3DH-CE/
    dirs_path: # please/insert/*below*/the/sub/directory(from_home_dir)/where/CSVs/are/located
      train: # we split train,val, and test according to 'train_val_test_split' variable above and the following sequence.
        - "01"
        - "02"
    one_hot_label: ${one_hot}
    version: v1
    dim: "3D"
    overlap: 1
    jump_frames: 1
    mul_vals: [2, 2, 2]
    filter_edges: True
    directed: True
    edge_feat_embed_dict:
      p: 1
      use_normalized_x: True
      normalized_features: False

    separate_models: ${separate_models}
    normalize_all_cols: False

    same_frame: False # must be false
    next_frame: True

    self_loop: True
    normalize: True
    debug_visualization: False
    which_preprocess: 'MinMax'
    drop_feat: []