
logger:
    # TensorBoard
    tensorboard:
        save_dir: "${log_dir}/gnn/tensorboard/"
        name: "${exp_name}"

    use_wandb: True
    # wandb:
    wandb:
        save_dir: "${log_dir}"
        project: "${exp_name}"


