
logger:
    # # CSVLogger built in PyTorch Lightning
    # csv:
    #     save_dir: "${log_dir}/gnn/csv/"
    #     name: "default"

    # TensorBoard
    tensorboard:
        save_dir: "${log_dir}/gnn/tensorboard/"
        name: "default"
